# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=50, verbose_name='Город нахождения стула')),
            ],
        ),
        migrations.CreateModel(
            name='Personages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Имя')),
                ('secondName', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок цитаты')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairNumber', models.PositiveSmallIntegerField(unique=True, verbose_name='Номмер стула')),
                ('description', models.TextField(verbose_name='Краткое описание действия')),
                ('result', models.BooleanField(verbose_name='Драгоценности найдены')),
                ('cityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cities', verbose_name='Город нахождения стула')),
                ('personages', models.ManyToManyField(to='home.Personages', verbose_name='Персонажи')),
            ],
        ),
    ]
