# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170902_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='personages',
            field=models.ManyToManyField(to='home.Personages', verbose_name='Персонажи'),
        ),
    ]
