# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170902_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='description',
            field=models.TextField(default='Описание города', verbose_name='Описание города'),
        ),
        migrations.AddField(
            model_name='cities',
            name='photo',
            field=models.CharField(default='/', max_length=100, verbose_name='Фотография города'),
        ),
    ]
